### PR TITLE
Add new Links and WorokItems (incl. cache)

### PR DESCRIPTION
**Pull request by giuliov**
[Review on Reviewable](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/38)

### CODE REVIEW

**Comment by giuliov** [comment]
Should fix #37; implements #29 and #30

**Comment by jessehouwing** [comment]
Great work, took up quite a few items it seems. Would love to see a few small name changes and the reintroduction of HasParent and HasChildren, simply for the simplicity sake in the scripts. HasRelation("Parent") just isn't as simple and aggregation across standard relations is done often. I'd almost opt to automatically include the methods for (most) standard relations out of the box.

---

Review status: 0 of 42 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[Aggregator.ConsoleApp/RunCommand.cs, line 67 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38#-Jt3Zy2tSe2CfkNwWt64)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/85376f10b1439953a62b9378fb1999a3e20f7dc1/Aggregator.ConsoleApp/RunCommand.cs#L67)):</sup>
Do we want to call this `runtime`? It feels a bit off to me, as it's a per request -runtime... 

---

<sup>**[Aggregator.Core/Configuration/TFSAggregatorSettings.cs, line 79 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38#-Jt3_P6z2KQ1ShdaQv2q)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/85376f10b1439953a62b9378fb1999a3e20f7dc1/Aggregator.Core/Configuration/TFSAggregatorSettings.cs#L79)):</sup>
Can we move this to a helper that accepts a Stream or StreamReader and the expected hash?

---

<sup>**[Aggregator.Core/Context/IRuntimeContext.cs, line 16 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38#-Jt3_gANNpnQxOofelkN)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/85376f10b1439953a62b9378fb1999a3e20f7dc1/Aggregator.Core/Context/IRuntimeContext.cs#L16)):</sup>
Does it make sense to provide access to VCS and WIT services from this context as well? That way we can probably completely hide away the IRequestContext itself, making it much easier to wrap this in the consoleapp and tests for example.

---

<sup>**[Aggregator.Core/EventProcessor.cs, line 32 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38#-Jt3aB_kmN0ubLDW4IvE)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/85376f10b1439953a62b9378fb1999a3e20f7dc1/Aggregator.Core/EventProcessor.cs#L32)):</sup>
Can we embed the work item store in the context, instead of the other way around. I'd prefer to see runtime.Store.Save(workitems) instead of this.Store.Save(runtime.Workitems)...

Again, runtime feels to Singleton in name. aggregationContext is probably better... I understand we don't want to "hide" RequestContext...

---

<sup>**[Aggregator.Core/Facade/WorkItemRepository.cs, line 53 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38#-Jt3aeTQsLcFoN5YrNxL)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/85376f10b1439953a62b9378fb1999a3e20f7dc1/Aggregator.Core/Facade/WorkItemRepository.cs#L53)):</sup>
You went the whole 9 yards, did you ;)> 

---

<sup>**[Aggregator.Core/Interfaces/IWorkItemLinkCollection.cs, line 7 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38#-Jt3bWVahWOIstf-n3Rb)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/85376f10b1439953a62b9378fb1999a3e20f7dc1/Aggregator.Core/Interfaces/IWorkItemLinkCollection.cs#L7)):</sup>
I had explicitly added HasParent and HasChildren as this will be a very common operation. The script involved to check for a relation will be much more verbose if one has to supply a IWorkItemLink instance.

Plus checking against the link instance makes it much harder to simply check against the link type at wildcard.

---

<sup>**[Aggregator.Core/Script/DotNetScriptEngine.cs, line 73 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38#-Jt3cPGG8LmYN39mOWUX)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/85376f10b1439953a62b9378fb1999a3e20f7dc1/Aggregator.Core/Script/DotNetScriptEngine.cs#L73)):</sup>
Looks much simpler than all the nested loops/

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38)

**Comment by giuliov** [comment]
<sup>**[Aggregator.Core/Facade/WorkItemRepository.cs, line 53 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38#-Jt3aeTQsLcFoN5YrNxL)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/85376f10b1439953a62b9378fb1999a3e20f7dc1/Aggregator.Core/Facade/WorkItemRepository.cs#L53)):</sup>
Yes

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38)

**Comment by giuliov** [comment]
<sup>**[Aggregator.Core/Interfaces/IWorkItemLinkCollection.cs, line 7 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38#-Jt3bWVahWOIstf-n3Rb)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/85376f10b1439953a62b9378fb1999a3e20f7dc1/Aggregator.Core/Interfaces/IWorkItemLinkCollection.cs#L7)):</sup>
HasXYZ moved from interface to extension class (IWorkItemExposedExtensions) to share code with tests.

Good suggestion to have similar helpers for links.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38)

**Comment by giuliov** [comment]
<sup>**[Aggregator.Core/Script/DotNetScriptEngine.cs, line 73 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38#-Jt3cPGG8LmYN39mOWUX)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/85376f10b1439953a62b9378fb1999a3e20f7dc1/Aggregator.Core/Script/DotNetScriptEngine.cs#L73)):</sup>
Not just simpler. They were plain wrong!
After refactoring of script compiling, it made no more sense. Instead caused the bug of unwanted execution.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38)

**Comment by giuliov** [comment]
<sup>**[Aggregator.Core/Script/DotNetScriptEngine.cs, line 73 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38#-Jt3cPGG8LmYN39mOWUX)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/85376f10b1439953a62b9378fb1999a3e20f7dc1/Aggregator.Core/Script/DotNetScriptEngine.cs#L73)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38)

**Comment by giuliov** [comment]
<sup>**[Aggregator.Core/Facade/WorkItemRepository.cs, line 53 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38#-Jt3aeTQsLcFoN5YrNxL)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/85376f10b1439953a62b9378fb1999a3e20f7dc1/Aggregator.Core/Facade/WorkItemRepository.cs#L53)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38)

**Comment by giuliov** [comment]
<sup>**[Aggregator.Core/Facade/WorkItemRepository.cs, line 53 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38#-Jt3aeTQsLcFoN5YrNxL)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/85376f10b1439953a62b9378fb1999a3e20f7dc1/Aggregator.Core/Facade/WorkItemRepository.cs#L53)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38)

**Comment by giuliov** [comment]
<sup>**[Aggregator.Core/Facade/WorkItemRepository.cs, line 53 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38#-Jt3aeTQsLcFoN5YrNxL)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/85376f10b1439953a62b9378fb1999a3e20f7dc1/Aggregator.Core/Facade/WorkItemRepository.cs#L53)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38)

**Comment by giuliov** [comment]
Reviewed 42 of 42 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38)

**Comment by giuliov** [comment]
The HasParent, HasChildren moved to be an extension, so no need to implement mocks for them.

Took note of the other suggestions, will update to PR

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/38)

**Pull request merged**
