### PR TITLE
Addition of ADOS 2022.1 RC Support + API Upgrades... (v16 -> v19)

### PR DESCRIPTION
**Pull request by M-Luke**
* Initial addition of ADOS 2022.1 RC Support + required API/Nuget Upgrades v16 -> v19 (16.205.0-preview -> 19.227.0-preview)
 * New 2022.1 Debug/Release build configuration addition + everything else that goes with it added.
 * WiX installer changes to support/add new ADOS 2022.1 build + support.
 * Minor tweaks/fixes noticed as doing the support additions.
 
 API + new Build Config added, as Builds of 2022 version were failing when using AZDO 2022.1 DLL's _(v16 to v19 API missmatch)_

 **Testing:**
-  Tested locally on Dev/QA instance of 2022.1 RC and appears to still be working fine... _(With our basic rule set)_ - Installed as plugin
-  Also tested using the Console (Build output of new Build locally) and that also seems to work as expected.
image
- Unit tests are also all passing still _(On new release build configuration)_
image

 
 
_**I believe this is all that is required to add in a new supported version + Builds. 
However if I have missed anything please say and I can go fix it.**_
 
 _Thanks In Advance_
 Luke

- - -
This change is [Reviewable](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/392)

### CODE REVIEW

**Comment by jessehouwing** [comment]
That looks pretty complete at first sight. Currently on my phone, so let me verify in the coming days.

**Comment by M-Luke** [comment]
> That looks pretty complete at first sight. Currently on my phone, so let me verify in the coming days.

No worries.

**Comment by jessehouwing** [comment]
Let me know whether it works!
https://github.com/tfsaggregator/tfsaggregator/releases/tag/2.7.0-beta.1

**Comment by M-Luke** [comment]
@jessehouwing Appears to be working fine from my quick/limited testing. 

- Auto-Select for correct version in the MSI seems to work. 
Screenshot 2023-10-01 231620
Screenshot 2023-10-01 231641
Screenshot 2023-10-01 231813
Screenshot 2023-10-01 231946

- The Plugin also appears to be working in 2022.1 RC as expected for my test rule set.
image

**Comment by jessehouwing** [comment]
Thanks for confirming! I've updated the pipelines and made sure we have the correct set of server binaries in our packages feed as well. Love your contributions, I rarely see on-prem customers anymore, but with people like you it's a breeze to keep this project running.

**Comment by M-Luke** [comment]
No worries 👍 

Tested on 2 other On-Prem instances this morning (A 2022.0.1 and a 2022.1 RC1) and both appear to be working fine with the installer also working as expected. _(Ruleset now works on both versions)_ 😄 

Thanks for getting it merged in and released so quickly.

**Pull request merged**
