### PR TITLE
Support for 2017.3 and 2018

### PR DESCRIPTION
**Pull request by giuliov**
Lack full regression testing.
MSI correctly recognize 2015.4 2017.3 and 2018 and installed plugin runs HelloWorld rule.

---
This change is [Reviewable](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/266)

### CODE REVIEW

**Comment by jessehouwing** [comment]
Looking good. This should also fix the templates open bug.

**Comment by jawn** [comment]
Can anyone see why this check fails?

**Comment by giuliov** [comment]
Because I cancelled the : there are still issues with the references

**Comment by dasMulli** [comment]
Have there been any breaking changes to the plugin? I did a quick test with the existing plugin dlls but tfs didn't seem to load them (at least no messages in the event log) but it might as well be a case of PEBCK.

**Comment by jessehouwing** [comment]
No breaking changes apart from a bug that broke the process template scope,
that should be fixed now, though you may need to update the name of the
template to match what the new api is returning.

**Comment by millusdk** [comment]
Any indication on when this will be merged, and a release that supports 2017.3 will be released?

**Comment by jessehouwing** [comment]
Releasing is easy. Finding the time to make sure we don't break anybody is
much harder.

**Comment by millusdk** [comment]
Of course, it is much more important not to break existing working stuff than to add support for new systems. I was just wondering if you had any indication of when it could be released, since we are very eager to update from 2017.2 to 2017.3, as it should fix some of the performance issues we currently experience

**Comment by japj** [comment]
Is the issue with references related to the change for IProjectService in Microsoft.TeamFoundation.Server.Types.dll and the subsequent references needed?

**Comment by jessehouwing** [comment]
No the reference issue happens with every major version due to all version
numbers changing and some breaking changes happening regularly. Mostly on
the server object model, which has quite a few dependencies on the
accompanying client object model unfortunately.

The project property switches from string to object was the one for 2017u2.
This also moved some types around. The fix for the procrss template scope
required the use of IprojectService, which we didn't need up until 2017u1.

**Comment by dasMulli** [comment]
I built a 2018 plugin from this PR after some fiddling with the build process (installer msbduild project seems to reference a different extended client nuget version as the 2018 packages.config). Managed to get our auto-activate/resolve rule working but another one doesn't but I really haven't looked into it much, will need to test a bit using the console.

**Comment by japj** [comment]
@jessehouwing so this does not have any relation with any API changes between 2017u2/2017u3 then?

**Comment by jessehouwing** [comment]
An api change between tfs 2017u1 and 2017u2 is the reason for the
IProjectService, which also required the new reference.

But the other issues stem from 2018 taking a dependency on a newer client
object model than the one 2017rtm shipped with.

Basically there are two different references problems with this solution

1. The TFS server object model which gets a new major version every time a
new major version of TFS ships and which is more prone to breaking even
between update packs as Microsoft doesn't consider these APIs to be
long-term supported. Plus the process template and work item areas are
currently being heavily refactored to support the. We VSTS process
functionality. This also more regularly takes on new versions of external
dependencies like the json  library and such.

2. The TFS client object model which is far more stable with regards to
it's interfaces, but which has seen some shuffling of types between
assemblies. Normally that wouldn't be an issue at runtime, as the
dependency is often just indirect and will resolve itself at runtime, but
we hit a few compile time dependencies unfortunately. 2018 for the first
time has decoupled the client object model version from the server object
model version so while 2018 server is 16.*, the client still targets 15.*,
though a higher version that. 2017 ships with.

For both we have encountered that these libraries require a different
framework reference, 2013 requires 4.5.1, 2015 4.6 etc. And the aspnet
mvc/we api libraries that come with that.

Because we deploy in process with the server we need to be absolutely sure
we are binary compatible with the assemblies that ship with the server.

This is why Giulio made the investment of the rest api version. Because
that completely decouple from the server process, we are far less dependent
on these references.

Apart from the dependencies there have been some breaking changes between
releases, both in major and minor releases unfortunately. That's why we
have a number of compiler constants in place to handle these differences.
It's also why we have I trounced our own implementations of some classes,
staying code compatible to the rules would otherwise not have been an
option.

Our decoction to retain support for older server versions is causing some
major pain at the moment. And even though I'm inclined to drop 2013,
currently we have too many people who are still moving from 2015  to 2017
to 2018. And even 2017 and 2018 currently account for 3 different code
bases with small differences (2017rtm, 2017u2 and 2018rtm).

Refactoring the solution structure completely or working in different
branches is an option, but requires quite some work.

Maintaining a test VM for every version and running tests on each an every
one of them costs a lot of time.

So we're a bit between a rock and a hard place e at the moment. We'd love
support from folks like you to make this all easier and to allow us to stay
up to date and backwards compatible. Your effort to help this along is
highly appreciated.

**Comment by japj** [comment]
Thank you for your detailed explanation!
The TFS 2017U3 server binaries (mentioned in PLACEHOLDER.txt) have version 15.117.x.y, does this relate to a NuGet Client package 15.117.0-preview? (and would 112 then relate to 2017U2 by any chance?)

Currently the packages.config contains a hardcoded '15.122.1-preview', while the References.targets contains 15.112.1, as you can see by https://github.com/japj/tfsaggregator/commit/ac05fe427c294716544d085fd071c277da44edb3
After this commit, I can atleast compile again for 2017U2 (using the 2017U3 server assemblies).

Would the 'correct' solution be to have 15.117 Nuget package references for 2017U3? Essentially separating it for every version of TFS?

**Comment by jessehouwing** [comment]
Correct, which is why there is a packages.config in the references folder.
The plan behind it was originally to overwrite the packages.config I. The
project or use an xslt to fix it as part of the build. This will work for
the CI build, but it breaks Visual Studio. A real solution requires some
hard work.

Currently you'd have to prepare your workspace to build an older version.
And the files in the project folders should reflect the latest version.

This is fine as long as we're just patching it to work, but it's hindering
the addition of new features.

**Comment by japj** [comment]
Maybe I am missing something, but if it is ok to "only" support building with VS2017, then you can use NuGet PackageReferences instead of package.json.
That could allow MSBuild properties to be used for version referencing instead of going to all kinds of crazy stuff dealing with package.json files?

See also https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

**Comment by jessehouwing** [comment]
That is indeed a feasible solution now. Though I am unsure how well visual
studio will handle conditional package references. And whether it supports
framework 4.5 all the way to 4.7. If that works, I'm all up for it.

**Comment by dasMulli** [comment]
VS restore doesn't listen to solution configuration changes so you'd have to do some sort of select&re-open dance but it is probably easier to set up `Directory.Build.props` / `.targets` files to specify the active version being developed since VS 2017 15.3 tracks changes to imported projects. And for build scripts the upcoming `15.5` release is going to introduce an easy way to do a safe restore&build operation in one invocation using `msbuild /restore /t:SomeTarget /p:PropertyAffectingRestoreAndBuild=foo`.

**Comment by jessehouwing** [comment]
Sounds like you know what to do ;). I'm usually on the latest visual studio
anyway. We'd love to get rid of these issues.

**Comment by dasMulli** [comment]
I'd be happy to take a stab at simplifying the build process based on recent NuGet / MSBuild / VS project system developments. I just may not have a lot of time to do this before January.

Happy to report that my Frankenstein build for 2018 works quite well, though we aren't using all features exhaustively. (just copy-cusotm-fields-from-parent and auto-activate/resolve rules)

**Comment by jessehouwing** [comment]
@dasMulli that would be highly appreciated.

**Comment by jessehouwing** [comment]
@giuliov can you add MSA:jhouwing@xpirit.com to the tfsaggregator visual studio instance?

**Comment by millusdk** [comment]
Any news on this issue?

**Comment by mbendtsen** [comment]
If you need a beta-tester on this, I'll be happy to assist. Using TFS 2018.

**Comment by jessehouwing** [comment]
I closed this pull request in favor of a new one. I've pushes the latest version to develop a couple of minutes ago. This includes TFS 2017u2,3 and TFS2018rtm support and fixes the TemplateScope issues. Building fromVisual Studio 2017 update 3 or later should work when building with the target TFS server installed on your system, we now depend on the new project system.

If people want to test, we're eager for feedback.

**Comment by andreasba77** [comment]
Hi,
(sorry, if this is not the proper place for posting this request:)
what is the name of the TFS Aggregator service? I have pretty much the same problem as in "TFS Aggregator doesn't work on TFS 2017". Installation via msi works fine, also repair-install confirms that the installation took place. However, I find no indication of any service that is running or tries to run. I have a script in the appropriate folder which can be executed via the console, but automatic triggering does not happen (or it happens and fails, but I found no trace for an error so far).
Any help is greatly appreciated!
Thanks, Andreas

**Comment by jessehouwing** [comment]
@andreasba77:
https://tfsaggregator.github.io/admin/logging/
https://tfsaggregator.github.io/admin/troubleshooting/

**Comment by jessehouwing** [comment]
If you have more specific issues, please open a new issue.

**Comment by andreasba77** [comment]
Thanks for the fast response! 
Unfortunately, I don't find the name of the service in there? I have the suspicion that it is not running at all.

**Comment by jessehouwing** [comment]
There is no windows service. The aggregator is loaded into the TFS process
directly.

**Comment by andreasba77** [comment]
Thanks for the hints!
We solved it by putting the new script into the existing policy-file. Before, we had it in a separate file (and thought it would still be found).

**Pull request closed without merging**
