### PR TITLE
Add script debugging support

### PR DESCRIPTION
**Pull request by DEllingsworth**
Added this for c#

[Review on Reviewable](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/49)

### CODE REVIEW

**Comment by jessehouwing** [comment]
I don't think we want to expose all the internal log events to the rules. I think it would make more sense to create a IRuleEvents.  I love the ideas you're adding, but an important part of it will be that we support all engines equally. It could be a more narrow interface which is also implemented by LogTextComposer.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[Aggregator.Core/Monitoring/TextLogComposer.cs, line 294 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/49#-Jx8ZF5cqSUaj4P6z4B2)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/289eb6c9152d8509381aff2220392162b6127a91/Aggregator.Core/Monitoring/TextLogComposer.cs#L294)):</sup>
Move to new interface IRuleLogEvents

---

<sup>**[Aggregator.Core/Monitoring/TextLogComposer.cs, line 298 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/49#-Jx8ZgXIcgZWJTrNCylX)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/289eb6c9152d8509381aff2220392162b6127a91/Aggregator.Core/Monitoring/TextLogComposer.cs#L298)):</sup>
If these are specific for rules, then maybe add the rule name and policy automatically?

---

<sup>**[Aggregator.Core/Script/DotNetScriptEngine.cs, line 41 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/49#-Jx8ZqeY1k5d0R5hssZI)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/289eb6c9152d8509381aff2220392162b6127a91/Aggregator.Core/Script/DotNetScriptEngine.cs#L41)):</sup>
Comments to check whether we really need System.Data.* still stand. I still think we only need System.Core.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/49)

**Comment by jessehouwing** [comment]
Please rebase onto latest due to merge conflicts.

**Comment by DEllingsworth** [comment]
I agree about IRuleEvents. I just could not seem to pass a different logger reference into the script file. I'll put some more effort into it.

**Comment by jessehouwing** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[Aggregator.Core/Script/CSharpScriptEngine.cs, line 32 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/49#-JxLtImPHQFHe1cCkJoz)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/289eb6c9152d8509381aff2220392162b6127a91/Aggregator.Core/Script/CSharpScriptEngine.cs#L32)):</sup>
Change this to IRuleEvents, but pass in the same logger. It's enough to hide the other methods by default. Make ILogEvents implement
 from IRuleEvents.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/49)

**Comment by DEllingsworth** [comment]
Created better pull request. Closing this one.

**Pull request closed without merging**
