### PR TITLE
Cascade console option #34

### PR DESCRIPTION
**Pull request by giuliov**
Implements #34 and fix some bug on template scope

[Review on Reviewable](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/57)

### CODE REVIEW

**Comment by jessehouwing** [comment]
Reviewed 16 of 21 files at r1.
Review status: 14 of 19 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[Aggregator.ConsoleApp/RequestContext.cs, line 36 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57#-K-4qxdDlZw7Lipe9N9q)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/485b5e2db232c5675f53a54cba83ff7c4bf1c662/Aggregator.ConsoleApp/RequestContext.cs#L36)):</sup>
This won't do. I know quite a few installs which have removed the /tfs/ virtual directory.

Why is this no longer using the TeamProjectCollection object?

---

<sup>**[Aggregator.Core/Configuration/TemplateScope.cs, line 52 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57#-K-4sWEr2csWUQIJ5Z_o)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/485b5e2db232c5675f53a54cba83ff7c4bf1c662/Aggregator.Core/Configuration/TemplateScope.cs#L52)):</sup>
Correct, possibly caused by the introduction of the cache.

---

<sup>**[Aggregator.Core/Configuration/TFSAggregatorSettings.cs, line 174 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57#-K-4seo-Qt5IjUE5GGj4)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/485b5e2db232c5675f53a54cba83ff7c4bf1c662/Aggregator.Core/Configuration/TFSAggregatorSettings.cs#L174)):</sup>
Any combo is valid. 

---

<sup>**[Aggregator.Core/EventProcessor.cs, line 155 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57#-K-4syX4RmQ05R8pdHV1)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/485b5e2db232c5675f53a54cba83ff7c4bf1c662/Aggregator.Core/EventProcessor.cs#L155)):</sup>
I want to do some work here to raise an event on pre/post save so we can hook into this point. The Rate Limiter needs this, you seem to need this. Right now this is closed to extension, open to modification. I'd like to change that.

---

<sup>**[Aggregator.Core/Script/PsScriptEngine.cs, line 43 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57#-K-4tGJ7oBs6MCWiP8Jv)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/485b5e2db232c5675f53a54cba83ff7c4bf1c662/Aggregator.Core/Script/PsScriptEngine.cs#L43)):</sup>
Is that the same logger as passed into the C# and VB.NEt script engine?

---

<sup>**[samples/TFSAggregator2.ServerPlugin.policies, line 3 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57#-K-4tOCcvXHuhw31zOoD)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/485b5e2db232c5675f53a54cba83ff7c4bf1c662/samples/TFSAggregator2.ServerPlugin.policies#L3)):</sup>
Forgot to add the Rate Limiter settings to the sample config.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57)

**Comment by giuliov** [comment]
Review status: 14 of 19 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[Aggregator.ConsoleApp/RequestContext.cs, line 36 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57#-K-4qxdDlZw7Lipe9N9q)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/485b5e2db232c5675f53a54cba83ff7c4bf1c662/Aggregator.ConsoleApp/RequestContext.cs#L36)):</sup>
Because the Name property returns the Collection URL, not the name. I struggled to find some neat way of getting this info from TFS. Ideas welcome.

---

<sup>**[Aggregator.Core/Configuration/TFSAggregatorSettings.cs, line 0 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57#-K-4seo-Qt5IjUE5GGj4)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/485b5e2db232c5675f53a54cba83ff7c4bf1c662/Aggregator.Core/Configuration/TFSAggregatorSettings.cs#L0)):</sup>
But at least one must be specified :-). Sadly it is not possible to delegate the check to XSD, must be done in code.

---

<sup>**[Aggregator.Core/Script/PsScriptEngine.cs, line 43 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57#-K-4tGJ7oBs6MCWiP8Jv)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/485b5e2db232c5675f53a54cba83ff7c4bf1c662/Aggregator.Core/Script/PsScriptEngine.cs#L43)):</sup>
Sh...! Fill fix.

---

<sup>**[samples/TFSAggregator2.ServerPlugin.policies, line 3 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57#-K-4tOCcvXHuhw31zOoD)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/485b5e2db232c5675f53a54cba83ff7c4bf1c662/samples/TFSAggregator2.ServerPlugin.policies#L3)):</sup>
You mean that we need to document them, but they pop up in all places.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57)

**Comment by jessehouwing** [comment]
Review status: 14 of 19 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[Aggregator.ConsoleApp/RequestContext.cs, line 0 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57#-K-4qxdDlZw7Lipe9N9q)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/485b5e2db232c5675f53a54cba83ff7c4bf1c662/Aggregator.ConsoleApp/RequestContext.cs#L0)):</sup>
There is a naming util class somewhere which will take the collection name from the uri. I'll look it up if you can't find it. 

---

<sup>**[Aggregator.Core/Configuration/TFSAggregatorSettings.cs, line 0 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57#-K-4seo-Qt5IjUE5GGj4)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/485b5e2db232c5675f53a54cba83ff7c4bf1c662/Aggregator.Core/Configuration/TFSAggregatorSettings.cs#L0)):</sup>
None would make it a noop, would be fine to me ;) 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57)

**Comment by jessehouwing** [comment]
Review status: 14 of 19 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[Aggregator.ConsoleApp/RequestContext.cs, line 36 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57#-K-4qxdDlZw7Lipe9N9q)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/485b5e2db232c5675f53a54cba83ff7c4bf1c662/Aggregator.ConsoleApp/RequestContext.cs#L36)):</sup>
Use  TfsTeamProjectColection.CataloNode.Resource.DisplayName or possibly Identifier. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57)

**Comment by giuliov** [comment]
Review status: 14 of 19 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[Aggregator.ConsoleApp/RequestContext.cs, line 36 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57#-K-4qxdDlZw7Lipe9N9q)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/485b5e2db232c5675f53a54cba83ff7c4bf1c662/Aggregator.ConsoleApp/RequestContext.cs#L36)):</sup>
Gotcha! Fixed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57)

**Comment by jessehouwing** [comment]
Reviewed 5 of 21 files at r1.
Review status: 12 of 27 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[docs/Scripting.md, line 137 \[r2\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57#-K-7lIUJm6qNrNRfXAvD)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/c1e15d7d4d21cb3b6f235e6f4bab9d99fd8bb0c0/docs/Scripting.md#L137)):</sup>
Needs a .HasParent check to prevent NullReferenceException

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57)

**Comment by jessehouwing** [comment]
Reviewed 15 of 15 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/57)

**Pull request merged**
