### PR TITLE
Global cache

### PR DESCRIPTION
**Pull request by giuliov**
Better performance avoiding recompiling rules each time

Not sure if any multi-threading bug lurking

[Review on Reviewable](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/35)

### CODE REVIEW

**Comment by jessehouwing** [comment]
I'd love it if we could refactor the Cache and the Settings and the Instance into a Context class that provides access to the required objects. It would make access in the console app easier as well as in the unit tests. Right now the responsibility of caching, context and configuration seem to be spread across a number of different objects.

It would also allow us to (if (part of) the context is cloned each time it enters into a new request, simply reload without having impact on concurrent requests. Right now reloading could do funny things.

The Context object would provide a clear abstraction between the rules processing and the loading of settings, repositories and other items and would thus separate the responsibility of processing clearly from caching and initialization. 

This may be a starting point, or we could decide to further improve this before committing.

---

Review status: 0 of 16 files reviewed, 5 unresolved discussions, all commit checks successful.

---

<sup>**[Aggregator.Core/Configuration/TFSAggregatorSettings.cs, line 43 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/35#-JqBCWSFU7GeehxE-WZd)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/3d8718ef595aed8c68c5e699026c64ff54467aed/Aggregator.Core/Configuration/TFSAggregatorSettings.cs#L43)):</sup>
Rename to IsValid this reads funny. Plus what does it validate? current signature suggests it validates the logger, which it doesn't. Store the logger in a static variable and don't pass it along or extract validation into a SettingsValidator class and pass the logger to its initialization.

---

<sup>**[Aggregator.Core/EventProcessor.cs, line 23 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/35#-JqBDFgAZADmIv80yRKA)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/3d8718ef595aed8c68c5e699026c64ff54467aed/Aggregator.Core/EventProcessor.cs#L23)):</sup>
Merge Cache and Settings into Context object (or wrap both in)

---

<sup>**[Aggregator.Core/ObjectCache.cs, line 50 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/35#-JqBDTsDh4sdo5JBE0z8)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/3d8718ef595aed8c68c5e699026c64ff54467aed/Aggregator.Core/ObjectCache.cs#L50)):</sup>
This would cause the settings file to be read multiple times. Can we lock one statement earlier? or was this deliberate?

---

<sup>**[Aggregator.ServerPlugin/WorkItemChangedEventHandler.cs, line 52 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/35#-JqBDf6hp_eqkVpCzkSV)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/3d8718ef595aed8c68c5e699026c64ff54467aed/Aggregator.ServerPlugin/WorkItemChangedEventHandler.cs#L52)):</sup>
Rename cache to context

---

<sup>**[Aggregator.ServerPlugin/WorkItemChangedEventHandler.cs, line 64 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/35#-JqBDibJxDHuFOl_9TFU)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/3d8718ef595aed8c68c5e699026c64ff54467aed/Aggregator.ServerPlugin/WorkItemChangedEventHandler.cs#L64)):</sup>
Move GetCVollectionUriFromContext to new context object

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/35)

**Comment by jessehouwing** [comment]
Review status: all files reviewed, 5 unresolved discussions, all commit checks successful.
Reviewed files:
- Aggregator.ConsoleApp/RunCommand.cs @ r1
- Aggregator.Core/Aggregator.Core.csproj @ r1
- Aggregator.Core/Configuration/TFSAggregatorSettings.cs @ r1
- Aggregator.Core/EventProcessor.cs @ r1
- Aggregator.Core/Monitoring/ILogEvents.cs @ r1
- Aggregator.Core/Monitoring/TextLogComposer.cs @ r1
- Aggregator.Core/ObjectCache.cs @ r1
- Aggregator.ServerPlugin/WorkItemChangedEventHandler.cs @ r1
- UnitTests.Core/Basics.cs @ r1
- UnitTests.Core/Cache.cs @ r1
- UnitTests.Core/Mock/ObjectCacheMock.cs @ r1
- UnitTests.Core/ScriptEngines.cs @ r1
- UnitTests.Core/Settings.cs @ r1
- UnitTests.Core/SingleParentChildAggregations.cs @ r1
- UnitTests.Core/TestHelpers.cs @ r1
- UnitTests.Core/UnitTests.Core.csproj @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/35)

**Comment by giuliov** [comment]
I like the idea of a context, it will make everything clearer.

**Comment by giuliov** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[Aggregator.Core/ObjectCache.cs, line 50 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/35#-JqBDTsDh4sdo5JBE0z8)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/3d8718ef595aed8c68c5e699026c64ff54467aed/Aggregator.Core/ObjectCache.cs#L50)):</sup>
The latter: I prefer a small risk of duplicating work, in case two requests enter simultaneously, to big risk of locking thread for too long.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/35)

**Comment by jessehouwing** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[Aggregator.Core/ObjectCache.cs, line 50 \[r1\]](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/35#-JqBDTsDh4sdo5JBE0z8)** ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/3d8718ef595aed8c68c5e699026c64ff54467aed/Aggregator.Core/ObjectCache.cs#L50)):</sup>
Just making sure it was intentional :)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tfsaggregator/tfsaggregator/35)

**Comment by giuliov** [comment]
Design is converging, but I am not able to have an integration test for cache removal on configuration file change.
I am also not satisfied with Engine: dropping the dependency from the IWorkItemRepository will simplify a lot, but I am hesitant doing it.

**Comment by jessehouwing** [comment]
I've merged this into Develop, as that was far ahead of this branch. Let's release a new beta and then merge into master.

**Pull request closed without merging**
