### PR TITLE
Added methods to add changeset / sourcefilelink (TFSVC) to workitems

### PR DESCRIPTION
**Pull request by AlexJott**
This could be useful when users add assign changesets to corresponding tasks and you want to see all angesets directly on the PBI or Bug.

Example rule:
```
<rule name="CopyChangesetToParent" appliesTo="Task">	
 <![CDATA[ 
	if (IsParentBugOrPbi(self, logger))
	{	
		var changeSetsInChild = self.AddedResourceLinks.Where(link => link.AddedResourceLinkType == AddedResourceLinkTypes.Changeset);
		foreach (var newExternalLink in changeSetsInChild)
               {         
		    var changeSetUri = newExternalLink.Resource;					
                    var taskChangeSetLink = self.ExternalLinks.SingleOrDefault(link => link.LinkedArtifactUri.Equals(changeSetUri));
                   if (taskChangeSetLink != null)
		   {
		      self.Parent.AddChangesetLink(changeSetUri, taskChangeSetLink.Comment);				
		   }		
		  else				
		  {
		      logger.Log(LogLevel.Error, "No changeset found on source");
		   }
            }				
	}			
]]>
</rule>

```

---
This change is [Reviewable](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/305)

### CODE REVIEW

**Comment by giuliov** [comment]
___
*[Aggregator.Core/Aggregator.Core/Interfaces/IWorkItemExposed.cs, line 53 at r1](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/305#-LHgQPZl3-j0v4RNOPZU:-LHgQPZm1hlkvh5X6oMH:b-c43u41) ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/4975c952dd3ec8f539b3a3383b9ab4628b977f68/Aggregator.Core/Aggregator.Core/Interfaces/IWorkItemExposed.cs#L53)):*
> ```Smalltalk
>         IEnumerable<IWorkItemExposed> GetRelatives(FluentQuery query);
> 
>         IEnumerable<Interfaces.AddedResourceLink> AddedResourceLinks { get; }
> ```

Why _Added_ and not simply `ResourceLinks`?

**Comment by giuliov** [comment]
___
*[Aggregator.Core/Aggregator.Core/Interfaces/IWorkItemExposed.cs, line 68 at r1](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/305#-LHgQlUiEOknFeZHnrNx:-LHgQlUiEOknFeZHnrNy:bo8ra0g) ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/4975c952dd3ec8f539b3a3383b9ab4628b977f68/Aggregator.Core/Aggregator.Core/Interfaces/IWorkItemExposed.cs#L68)):*
> ```Smalltalk
>         void AddHyperlink(string destination, string message);
> 
>         void AddChangesetLink(string changeSetUri, string comment);
> ```

This is TFVC specific, should we have an `AddCommitLink` for Git too?

**Comment by giuliov** [comment]
___
*[Aggregator.Core/Aggregator.Core/Script/DotNetScriptEngine{TCodeDomProvider}.cs, line 130 at r1](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/305#-LHgR1U5EfsWLjABLHwt:-LHgR1U67LIoTpWm3wKe:b-8vg8wr) ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/4975c952dd3ec8f539b3a3383b9ab4628b977f68/Aggregator.Core/Aggregator.Core/Script/DotNetScriptEngine{TCodeDomProvider}.cs#L130)):*
> ```Smalltalk
>             if (classForScript == null)
>             {
>                 this.Logger.FailureLoadingScript($"No compiled class found for {scriptName}");
> ```

There is a misunderstanding here: each event is represented by an `ILogEvents` method and you call it where the event arise passing parameters. The message itself is in the `TextLogComposer` class.
In this case could be `FailureLoadingScriptDueToClassNotFoundError(scriptName)`

**Comment by giuliov** [comment]
___
*[Aggregator.Core/Aggregator.Core/Script/DotNetScriptEngine{TCodeDomProvider}.cs, line 259 at r1](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/305#-LHgSE350q9jcJOCHSTQ:-LHgSE36D67qwfHFYjBb:be6o9or) ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/4975c952dd3ec8f539b3a3383b9ab4628b977f68/Aggregator.Core/Aggregator.Core/Script/DotNetScriptEngine{TCodeDomProvider}.cs#L259)):*
> ```Smalltalk
>                 }
> 
>                 this.Logger.FailureLoadingScript($"Error(s) in '{scriptName}':{Environment.NewLine}{errors}");
> ```

In this case I would pass the `Errors` property as a parameter to the logging method, e.g. `CompilerErrorForScript(scriptName,this.compilerResult.Errors)`

**Review by giuliov — COMMENTED** [review]
> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/305)* status: all files reviewed, 4 unresolved discussions (waiting on @AlexJott)

**Review by jessehouwing — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/305)* status: all files reviewed, 14 unresolved discussions (waiting on @AlexJott)

___
*[Aggregator.ConsoleApp/Notification.cs, line 64 at r1](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/305#-LHgjZdLBK8NBLASTqM4:-LHgjZdLBK8NBLASTqM5:b-74y3h2) ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/4975c952dd3ec8f539b3a3383b9ab4628b977f68/Aggregator.ConsoleApp/Notification.cs#L64)):*
> ```Smalltalk
>         }
> 
>         public IEnumerable<AddedResourceLink> AddedResourceLinks { get; private set; }
> ```

I don't see why we'd need to track this on the INotification. Currently we don't expose which changes were made to a work item (which fields, links etc), so this is breaking with our tradition. Also this won't be available for say `self.Parent` or `self.Children`.

I like being able to see the changes as registered in `self`, but that would be part of a larger change and I think I'd like to see that as an inheritance of IWorkItem for the work item triggering the notification. e.g. ITriggeringWorkItem and include: `ChangedFields`, `ChangedLinks` and then have a `ChangeType` on the `ChangedLink`item to be either `Added`. `Removed` or `Changed`. Otherwise we'll see an explosion of new properties on INotification and people may assume these are available everywhere.
___
*[Aggregator.Core/Aggregator.Core/Aggregator.Core.csproj, line 15 at r1](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/305#-LHgkpPK3JOZHePFuuRw:-LHgkpPK3JOZHePFuuRx:b-v7iup3) ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/4975c952dd3ec8f539b3a3383b9ab4628b977f68/Aggregator.Core/Aggregator.Core/Aggregator.Core.csproj#L15)):*
> ```XML
>     <FileAlignment>512</FileAlignment>
>     <Configurations>Debug;Release;Debug-2013;Release-2013;Debug-2015;Release-2015;Debug-2015.1;Release-2015.1;Debug-2015.2;Release-2015.2;Debug-2017;Release-2017;Debug-2017.2;Release-2017.2;Debug-2018;Release-2018</Configurations>
>     <CodeAnalysisRuleSet>..\TFS-Aggregator-2.ruleset</CodeAnalysisRuleSet>
> ```

This seems to have snuck in. The Ruleset was renamed, please do an interactive rebase to remove this change. See:

https://github.com/tfsaggregator/tfsaggregator/blob/develop/tfs-aggregator.ruleset
___
*[Aggregator.Core/Aggregator.Core/Facade/WorkItemWrapper.cs, line 165 at r1](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/305#-LHgl7_-2OkewpfnKhtE:-LHgl7_-2OkewpfnKhtF:bsgdwln) ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/4975c952dd3ec8f539b3a3383b9ab4628b977f68/Aggregator.Core/Aggregator.Core/Facade/WorkItemWrapper.cs#L165)):*
> ```Smalltalk
>         }
> 
>         public IReadOnlyList<ExternalLink> ExternalLinks
> ```

Does this mean that added links won't be reflected until after save? That means that it'll be hard to detect whether a link was already added, but is awaiting save. I'd prefer a ExternalLinksCollectionWrapper here that handles the correct `Add`/`Remove` logic. Or The result shouldn't be cached.
___
*[Aggregator.Core/Aggregator.Core/Facade/WorkItemWrapper.cs, line 366 at r1](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/305#-LHgihmw06nrNBWD7695:-LHgihmw06nrNBWD7696:b-zebnly) ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/4975c952dd3ec8f539b3a3383b9ab4628b977f68/Aggregator.Core/Aggregator.Core/Facade/WorkItemWrapper.cs#L366)):*
> ```Smalltalk
>         {
>             var link = new ExternalLink(registeredLinkType, uri) { Comment = comment };
>             if (!this.workItem.Links.OfType<ExternalLink>().Any(exLink => exLink.BaseType.Equals(BaseLinkType.ExternalLink) && exLink.LinkedArtifactUri.Equals(link.LinkedArtifactUri, StringComparison.InvariantCultureIgnoreCase)))
> ```

Looks like the `exLink.BaseType.Equals(BaseLinkType.ExternalLink` isn't needed, since you're already calling `OfType`
___
*[Aggregator.Core/Aggregator.Core/Interfaces/AddedResourceLink.cs, line 17 at r1](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/305#-LHglWY5Ds2vPvREylWC:-LHglWY5Ds2vPvREylWD:btfc7rx) ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/4975c952dd3ec8f539b3a3383b9ab4628b977f68/Aggregator.Core/Aggregator.Core/Interfaces/AddedResourceLink.cs#L17)):*
> ```Smalltalk
>             get
>             {
>                 if (this.Resource.StartsWith(@"vstfs:///VersionControl/Changeset/"))
> ```

Can we move these to a static, or grab them from the TFS Client Object Model somewhere?
___
*[Aggregator.Core/Aggregator.Core/Interfaces/IWorkItem.cs, line 2 at r1](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/305#-LHgliYS9nuMUcMUUiAE:-LHgliYS9nuMUcMUUiAF:b-bqthtp) ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/4975c952dd3ec8f539b3a3383b9ab4628b977f68/Aggregator.Core/Aggregator.Core/Interfaces/IWorkItem.cs#L2)):*
> ```Smalltalk
> using System.Collections;
> using System.Collections.Generic;
> ```

Seems an irrelevant change
___
*[Aggregator.Core/Aggregator.Core/Interfaces/IWorkItemExposed.cs, line 5 at r1](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/305#-LHglpRY4UFmQ8AZPOM2:-LHglpRY4UFmQ8AZPOM3:buw09kg) ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/4975c952dd3ec8f539b3a3383b9ab4628b977f68/Aggregator.Core/Aggregator.Core/Interfaces/IWorkItemExposed.cs#L5)):*
> ```Smalltalk
> 
> using Aggregator.Core.Navigation;
> using Microsoft.TeamFoundation.WorkItemTracking.Client;
> ```

Is this dependency needed? Shouldn't this be hidden behind a Wrapper class?
___
*[Aggregator.Core/Aggregator.Core/Interfaces/IWorkItemExposed.cs, line 68 at r1](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/305#-LHgQlUiEOknFeZHnrNx:-LHgj0EB0qCHWsdiK9fi:bjyjh4e) ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/4975c952dd3ec8f539b3a3383b9ab4628b977f68/Aggregator.Core/Aggregator.Core/Interfaces/IWorkItemExposed.cs#L68)):*
<details><summary><i>Previously, giuliov (Giulio Vian) wrote…</i></summary><blockquote>

This is TFVC specific, should we have an `AddCommitLink` for Git too?
</blockquote></details>

I'd certainly like that.
___
*[Aggregator.Core/Aggregator.Core/Script/DotNetScriptEngine{TCodeDomProvider}.cs, line 137 at r1](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/305#-LHgjFBn02apXfCPAFIE:-LHgjFBn02apXfCPAFIF:brhumzf) ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/4975c952dd3ec8f539b3a3383b9ab4628b977f68/Aggregator.Core/Aggregator.Core/Script/DotNetScriptEngine{TCodeDomProvider}.cs#L137)):*
> ```Smalltalk
>             if (interfaceForScript == null)
>             {
>                 this.Logger.FailureLoadingScript($"No implementation of 'IDotNetScript' in class '{classForScript.Name}' found for {scriptName}");
> ```

Same here 
___
*[Aggregator.Core/Aggregator.Core/Script/DotNetScriptEngine{TCodeDomProvider}.cs, line 144 at r1](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/305#-LHgjGlmCJXGRXcCeheD:-LHgjGln3ZElfTA1aSqP:b-2guby3) ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/4975c952dd3ec8f539b3a3383b9ab4628b977f68/Aggregator.Core/Aggregator.Core/Script/DotNetScriptEngine{TCodeDomProvider}.cs#L144)):*
> ```Smalltalk
>             if (constructor == null || !constructor.IsPublic)
>             {
>                 this.Logger.FailureLoadingScript($"No constructor in class '{classForScript.Name}' found for {scriptName}");
> ```

same here
___
*[Aggregator.Core/Aggregator.Core/Script/DotNetScriptEngine{TCodeDomProvider}.cs, line 152 at r1](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/305#-LHgjHem7ISEplKWXPts:-LHgjHem7ISEplKWXPtt:b-2guby3) ([raw file](https://github.com/tfsaggregator/tfsaggregator/blob/4975c952dd3ec8f539b3a3383b9ab4628b977f68/Aggregator.Core/Aggregator.Core/Script/DotNetScriptEngine{TCodeDomProvider}.cs#L152)):*
> ```Smalltalk
>             if (scriptObject == null)
>             {
>                 this.Logger.FailureLoadingScript($"Calling constructor in class '{classForScript.Name}' for {scriptName} failed");
> ```

same here

**Review by jessehouwing — COMMENTED** [review]
I've added my feedback.This is a great addition and it's already shaping up nicely. I'd like to see a couple of improvements before we take it in, if you need help, shout!

> *[Reviewable](https://reviewable.io/reviews/tfsaggregator/tfsaggregator/305#-:-LHglyAH-pGbn_utMK4Z:b-bllqlt)* status: all files reviewed, 14 unresolved discussions (waiting on @AlexJott and @giuliov)

**Comment by jessehouwing** [comment]
@AlexJott Any update on your end?

**Comment by AlexJott** [comment]
Sorry for delay, I did some adjustments - but I'm finally not done. It takes some time because TFS maintenance is not my main task...

**Pull request closed without merging**
